spring:
  kafka:
    consumer:
      auto-offset-reset: earliest

kafka:
  bootstrapAddress: 'http://localhost:29092'
  topic:
    name: 'topic1'
    partitionsCount: 10
    replicasCount: 1
  replyTopic:
    name: 'topic2'
    replyName: 'reply-topic'
    partitionsCount: 10
    replicasCount: 1