kafka:
  bootstrapAddress: 'http://localhost:29092'
  topic:
    name: 'topic1'
    partitionsCount: 10
    replicasCount: 1
  replyTopic:
    name: 'topic2'
    replyName: 'reply-topic'
    groupId: 'reply-group'
    partitionsCount: 10
    replicasCount: 1
